### ISSUE TITLE
Problems with albopictus for python

### ISSUE THREAD

**Issue by lalfaroUNA** [kerguler/albopictus#3]
Dear Kamil, here the problem (same case with 1.11.0 version):

 Last login: Thu Jan 23 21:56:05 on ttys000
(base) LUISs-MacBook-Pro:~ lalfaro$ pip install albopictus-0.3.tar.gz
Processing ./albopictus-0.3.tar.gz
Building wheels for collected packages: albopictus
  Building wheel for albopictus (setup.py) ... done
  Created wheel for albopictus: filename=albopictus-0.3-cp37-cp37m-macosx_10_9_x86_64.whl size=796327 sha256=969323f346839b03d717b269a95854d582179a2c24714a96a24adfe632c29f64
  Stored in directory: /Users/lalfaro/Library/Caches/pip/wheels/e7/57/75/1f71c7f4925106643967b13ed12fbaa8cab4cde08af32d6d37
Successfully built albopictus
Installing collected packages: albopictus
  Attempting uninstall: albopictus
    Found existing installation: albopictus 0.3
    Uninstalling albopictus-0.3:
      Successfully uninstalled albopictus-0.3
Successfully installed albopictus-0.3
(base) LUISs-MacBook-Pro:~ lalfaro$ python
Python 3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import albopictus
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.7/site-packages/albopictus/__init__.py", line 71, in <module>
    from readModel import prepareModel
ModuleNotFoundError: No module named 'readModel'

**Comment by kerguler** [comment]
Dear Luis,
Thanks for posting the issue here.
Indeed, there seems to be problem with version 0.3.
While I am looking into it, I should note that I didn't observe the same problem with 1.11.
Please see the output below.
Could you please check?

```
(albotest) kamil@x86_64-apple-darwin13 Downloads % pip install albopictus-0.3.tar.gz 
Processing ./albopictus-0.3.tar.gz
Building wheels for collected packages: albopictus
  Running setup.py bdist_wheel for albopictus ... done
  Stored in directory: /Users/kamil/Library/Caches/pip/wheels/f6/20/d5/8d148e9c697b05706f367fc84e96c71d3ca1a60984efb8191f
Successfully built albopictus
Installing collected packages: albopictus
  Found existing installation: albopictus 1.12.2
    Uninstalling albopictus-1.12.2:
      Successfully uninstalled albopictus-1.12.2
Successfully installed albopictus-0.3
(albotest) kamil@x86_64-apple-darwin13 Downloads % python
Python 3.7.0 (default, Jul 23 2018, 20:22:55) 
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import albopictus
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/albopictus/__init__.py", line 71, in <module>
    from readModel import prepareModel
ModuleNotFoundError: No module named 'readModel'
>>> quit()
```

```
(albotest) kamil@x86_64-apple-darwin13 Downloads % pip install albopictus-1.11.0.tar.gz 
Processing ./albopictus-1.11.0.tar.gz
Building wheels for collected packages: albopictus
  Running setup.py bdist_wheel for albopictus ... done
  Stored in directory: /Users/kamil/Library/Caches/pip/wheels/df/60/df/8b588d1566bc726594340849b4f9413486a32ba4cf8f61717c
Successfully built albopictus
Installing collected packages: albopictus
  Found existing installation: albopictus 0.3
    Uninstalling albopictus-0.3:
      Successfully uninstalled albopictus-0.3
Successfully installed albopictus-1.11.0
(albotest) kamil@x86_64-apple-darwin13 Downloads % python
Python 3.7.0 (default, Jul 23 2018, 20:22:55) 
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import albopictus
Setting up RNG vectorst
Setting up RNG chikv
Setting up RNG sandfly
>>> 
```

**Comment by lalfaroUNA** [comment]
OK, I try to install 1.11.0 version and here the problem:

Last login: Fri Jan 24 09:11:47 on ttys000
(base) LUISs-MacBook-Pro:~ lalfaro$ pip install albopictus-1.11.0.tar.gz
Processing ./albopictus-1.11.0.tar.gz
Building wheels for collected packages: albopictus
  Building wheel for albopictus (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/d1/v9s6m4bj68vfdt_035d3qppw0000gn/T/pip-req-build-qop4t5wd/setup.py'"'"'; __file__='"'"'/private/var/folders/d1/v9s6m4bj68vfdt_035d3qppw0000gn/T/pip-req-build-qop4t5wd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/d1/v9s6m4bj68vfdt_035d3qppw0000gn/T/pip-wheel-niimozi1
       cwd: /private/var/folders/d1/v9s6m4bj68vfdt_035d3qppw0000gn/T/pip-req-build-qop4t5wd/
  Complete output (85 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.7
  creating build/lib.macosx-10.9-x86_64-3.7/albopictus
  copying src/albopictus/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/albopictus
  creating build/lib.macosx-10.9-x86_64-3.7/albopictus/readModel
  copying src/albopictus/readModel/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/albopictus/readModel
  creating build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior
  copying src/albopictus/setPrior/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior
  creating build/lib.macosx-10.9-x86_64-3.7/albopictus/plotPos
  copying src/albopictus/plotPos/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/albopictus/plotPos
  creating build/lib.macosx-10.9-x86_64-3.7/albopictus/accessory
  copying src/albopictus/accessory/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/albopictus/accessory
  creating build/lib.macosx-10.9-x86_64-3.7/albopictus/population
  copying src/albopictus/population/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/albopictus/population
  creating build/lib.macosx-10.9-x86_64-3.7/albopictus/dataSurv
  copying src/albopictus/dataSurv/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/albopictus/dataSurv
  running egg_info
  writing src/albopictus.egg-info/PKG-INFO
  writing dependency_links to src/albopictus.egg-info/dependency_links.txt
  writing top-level names to src/albopictus.egg-info/top_level.txt
  reading manifest file 'src/albopictus.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'src/albopictus.egg-info/SOURCES.txt'
  copying src/albopictus/gamma.c -> build/lib.macosx-10.9-x86_64-3.7/albopictus
  copying src/albopictus/gamma.h -> build/lib.macosx-10.9-x86_64-3.7/albopictus
  copying src/albopictus/incubator.c -> build/lib.macosx-10.9-x86_64-3.7/albopictus
  copying src/albopictus/incubator.h -> build/lib.macosx-10.9-x86_64-3.7/albopictus
  copying src/albopictus/incubator03.c -> build/lib.macosx-10.9-x86_64-3.7/albopictus
  copying src/albopictus/incubator03.h -> build/lib.macosx-10.9-x86_64-3.7/albopictus
  copying src/albopictus/modelAalbopictus03.c -> build/lib.macosx-10.9-x86_64-3.7/albopictus
  copying src/albopictus/modelAalbopictus08.c -> build/lib.macosx-10.9-x86_64-3.7/albopictus
  copying src/albopictus/modelAalbopictus13.c -> build/lib.macosx-10.9-x86_64-3.7/albopictus
  copying src/albopictus/modelAalbopictus18.c -> build/lib.macosx-10.9-x86_64-3.7/albopictus
  copying src/albopictus/modelStochAlbopictus.c -> build/lib.macosx-10.9-x86_64-3.7/albopictus
  copying src/albopictus/modelStochCHIKV.c -> build/lib.macosx-10.9-x86_64-3.7/albopictus
  copying src/albopictus/modelStochSand.c -> build/lib.macosx-10.9-x86_64-3.7/albopictus
  copying src/albopictus/ran_gen.c -> build/lib.macosx-10.9-x86_64-3.7/albopictus
  copying src/albopictus/ran_gen.h -> build/lib.macosx-10.9-x86_64-3.7/albopictus
  copying src/albopictus/spop.c -> build/lib.macosx-10.9-x86_64-3.7/albopictus
  copying src/albopictus/spop.h -> build/lib.macosx-10.9-x86_64-3.7/albopictus
  copying src/albopictus/spop01.c -> build/lib.macosx-10.9-x86_64-3.7/albopictus
  copying src/albopictus/spop01.h -> build/lib.macosx-10.9-x86_64-3.7/albopictus
  copying src/albopictus/uthash.h -> build/lib.macosx-10.9-x86_64-3.7/albopictus
  creating build/lib.macosx-10.9-x86_64-3.7/albopictus/data
  copying src/albopictus/data/climate.json -> build/lib.macosx-10.9-x86_64-3.7/albopictus/data
  copying src/albopictus/data/posterior.json -> build/lib.macosx-10.9-x86_64-3.7/albopictus/data
  copying src/albopictus/data/prior03.json -> build/lib.macosx-10.9-x86_64-3.7/albopictus/data
  copying src/albopictus/data/prior08.json -> build/lib.macosx-10.9-x86_64-3.7/albopictus/data
  copying src/albopictus/data/prior13.json -> build/lib.macosx-10.9-x86_64-3.7/albopictus/data
  copying src/albopictus/data/prior18.json -> build/lib.macosx-10.9-x86_64-3.7/albopictus/data
  copying src/albopictus/data/priorSand.json -> build/lib.macosx-10.9-x86_64-3.7/albopictus/data
  creating build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
  copying src/albopictus/setPrior/data/albopictus_F4_temp.txt -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
  copying src/albopictus/setPrior/data/albopictus_d1_temp.txt -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
  copying src/albopictus/setPrior/data/albopictus_d2_temp.txt -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
  copying src/albopictus/setPrior/data/albopictus_d3_temp.txt -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
  copying src/albopictus/setPrior/data/albopictus_d4_temp.txt -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
  copying src/albopictus/setPrior/data/albopictus_gtc_temp.txt -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
  copying src/albopictus/setPrior/data/albopictus_n23_dev.txt -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
  copying src/albopictus/setPrior/data/albopictus_n23_surv.txt -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
  copying src/albopictus/setPrior/data/albopictus_n23_temp.txt -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
  copying src/albopictus/setPrior/data/albopictus_p0_temp.txt -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
  copying src/albopictus/setPrior/data/albopictus_p1_temp.txt -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
  copying src/albopictus/setPrior/data/albopictus_p2_temp.txt -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
  copying src/albopictus/setPrior/data/albopictus_p3_temp.txt -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
  copying src/albopictus/setPrior/data/albopictus_tbm_temp.txt -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
  running build_ext
  building 'albopictus.modelAalbopictus03' extension
  Warning: Can't read registry to find the necessary compiler setting
  Make sure that Python modules winreg, win32api or win32con are installed.
  C compiler: gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/anaconda3/include -arch x86_64 -I/opt/anaconda3/include -arch x86_64
  
  creating build/temp.macosx-10.9-x86_64-3.7
  creating build/temp.macosx-10.9-x86_64-3.7/src
  creating build/temp.macosx-10.9-x86_64-3.7/src/albopictus
  compile options: '-I/usr/local/include -I/opt/anaconda3/include/python3.7m -c'
  gcc: src/albopictus/modelAalbopictus03.cgcc: src/albopictus/incubator03.c
  
  gcc -bundle -undefined dynamic_lookup -L/opt/anaconda3/lib -arch x86_64 -L/opt/anaconda3/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.9-x86_64-3.7/src/albopictus/incubator03.o build/temp.macosx-10.9-x86_64-3.7/src/albopictus/modelAalbopictus03.o -L/usr/local/lib -lgsl -lgslcblas -lstdc++ -o build/lib.macosx-10.9-x86_64-3.7/albopictus/modelAalbopictus03.cpython-37m-darwin.so
  ld: library not found for -lgsl
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  error: Command "gcc -bundle -undefined dynamic_lookup -L/opt/anaconda3/lib -arch x86_64 -L/opt/anaconda3/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.9-x86_64-3.7/src/albopictus/incubator03.o build/temp.macosx-10.9-x86_64-3.7/src/albopictus/modelAalbopictus03.o -L/usr/local/lib -lgsl -lgslcblas -lstdc++ -o build/lib.macosx-10.9-x86_64-3.7/albopictus/modelAalbopictus03.cpython-37m-darwin.so" failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for albopictus
  Running setup.py clean for albopictus
Failed to build albopictus
Installing collected packages: albopictus
  Attempting uninstall: albopictus
    Found existing installation: albopictus 0.3
    Uninstalling albopictus-0.3:
      Successfully uninstalled albopictus-0.3
    Running setup.py install for albopictus ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/d1/v9s6m4bj68vfdt_035d3qppw0000gn/T/pip-req-build-qop4t5wd/setup.py'"'"'; __file__='"'"'/private/var/folders/d1/v9s6m4bj68vfdt_035d3qppw0000gn/T/pip-req-build-qop4t5wd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/d1/v9s6m4bj68vfdt_035d3qppw0000gn/T/pip-record-3kvum1g8/install-record.txt --single-version-externally-managed --compile --install-headers /opt/anaconda3/include/python3.7m/albopictus
         cwd: /private/var/folders/d1/v9s6m4bj68vfdt_035d3qppw0000gn/T/pip-req-build-qop4t5wd/
    Complete output (85 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.7
    creating build/lib.macosx-10.9-x86_64-3.7/albopictus
    copying src/albopictus/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/albopictus
    creating build/lib.macosx-10.9-x86_64-3.7/albopictus/readModel
    copying src/albopictus/readModel/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/albopictus/readModel
    creating build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior
    copying src/albopictus/setPrior/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior
    creating build/lib.macosx-10.9-x86_64-3.7/albopictus/plotPos
    copying src/albopictus/plotPos/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/albopictus/plotPos
    creating build/lib.macosx-10.9-x86_64-3.7/albopictus/accessory
    copying src/albopictus/accessory/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/albopictus/accessory
    creating build/lib.macosx-10.9-x86_64-3.7/albopictus/population
    copying src/albopictus/population/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/albopictus/population
    creating build/lib.macosx-10.9-x86_64-3.7/albopictus/dataSurv
    copying src/albopictus/dataSurv/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/albopictus/dataSurv
    running egg_info
    writing src/albopictus.egg-info/PKG-INFO
    writing dependency_links to src/albopictus.egg-info/dependency_links.txt
    writing top-level names to src/albopictus.egg-info/top_level.txt
    reading manifest file 'src/albopictus.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'src/albopictus.egg-info/SOURCES.txt'
    copying src/albopictus/gamma.c -> build/lib.macosx-10.9-x86_64-3.7/albopictus
    copying src/albopictus/gamma.h -> build/lib.macosx-10.9-x86_64-3.7/albopictus
    copying src/albopictus/incubator.c -> build/lib.macosx-10.9-x86_64-3.7/albopictus
    copying src/albopictus/incubator.h -> build/lib.macosx-10.9-x86_64-3.7/albopictus
    copying src/albopictus/incubator03.c -> build/lib.macosx-10.9-x86_64-3.7/albopictus
    copying src/albopictus/incubator03.h -> build/lib.macosx-10.9-x86_64-3.7/albopictus
    copying src/albopictus/modelAalbopictus03.c -> build/lib.macosx-10.9-x86_64-3.7/albopictus
    copying src/albopictus/modelAalbopictus08.c -> build/lib.macosx-10.9-x86_64-3.7/albopictus
    copying src/albopictus/modelAalbopictus13.c -> build/lib.macosx-10.9-x86_64-3.7/albopictus
    copying src/albopictus/modelAalbopictus18.c -> build/lib.macosx-10.9-x86_64-3.7/albopictus
    copying src/albopictus/modelStochAlbopictus.c -> build/lib.macosx-10.9-x86_64-3.7/albopictus
    copying src/albopictus/modelStochCHIKV.c -> build/lib.macosx-10.9-x86_64-3.7/albopictus
    copying src/albopictus/modelStochSand.c -> build/lib.macosx-10.9-x86_64-3.7/albopictus
    copying src/albopictus/ran_gen.c -> build/lib.macosx-10.9-x86_64-3.7/albopictus
    copying src/albopictus/ran_gen.h -> build/lib.macosx-10.9-x86_64-3.7/albopictus
    copying src/albopictus/spop.c -> build/lib.macosx-10.9-x86_64-3.7/albopictus
    copying src/albopictus/spop.h -> build/lib.macosx-10.9-x86_64-3.7/albopictus
    copying src/albopictus/spop01.c -> build/lib.macosx-10.9-x86_64-3.7/albopictus
    copying src/albopictus/spop01.h -> build/lib.macosx-10.9-x86_64-3.7/albopictus
    copying src/albopictus/uthash.h -> build/lib.macosx-10.9-x86_64-3.7/albopictus
    creating build/lib.macosx-10.9-x86_64-3.7/albopictus/data
    copying src/albopictus/data/climate.json -> build/lib.macosx-10.9-x86_64-3.7/albopictus/data
    copying src/albopictus/data/posterior.json -> build/lib.macosx-10.9-x86_64-3.7/albopictus/data
    copying src/albopictus/data/prior03.json -> build/lib.macosx-10.9-x86_64-3.7/albopictus/data
    copying src/albopictus/data/prior08.json -> build/lib.macosx-10.9-x86_64-3.7/albopictus/data
    copying src/albopictus/data/prior13.json -> build/lib.macosx-10.9-x86_64-3.7/albopictus/data
    copying src/albopictus/data/prior18.json -> build/lib.macosx-10.9-x86_64-3.7/albopictus/data
    copying src/albopictus/data/priorSand.json -> build/lib.macosx-10.9-x86_64-3.7/albopictus/data
    creating build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
    copying src/albopictus/setPrior/data/albopictus_F4_temp.txt -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
    copying src/albopictus/setPrior/data/albopictus_d1_temp.txt -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
    copying src/albopictus/setPrior/data/albopictus_d2_temp.txt -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
    copying src/albopictus/setPrior/data/albopictus_d3_temp.txt -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
    copying src/albopictus/setPrior/data/albopictus_d4_temp.txt -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
    copying src/albopictus/setPrior/data/albopictus_gtc_temp.txt -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
    copying src/albopictus/setPrior/data/albopictus_n23_dev.txt -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
    copying src/albopictus/setPrior/data/albopictus_n23_surv.txt -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
    copying src/albopictus/setPrior/data/albopictus_n23_temp.txt -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
    copying src/albopictus/setPrior/data/albopictus_p0_temp.txt -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
    copying src/albopictus/setPrior/data/albopictus_p1_temp.txt -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
    copying src/albopictus/setPrior/data/albopictus_p2_temp.txt -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
    copying src/albopictus/setPrior/data/albopictus_p3_temp.txt -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
    copying src/albopictus/setPrior/data/albopictus_tbm_temp.txt -> build/lib.macosx-10.9-x86_64-3.7/albopictus/setPrior/data
    running build_ext
    building 'albopictus.modelAalbopictus03' extension
    Warning: Can't read registry to find the necessary compiler setting
    Make sure that Python modules winreg, win32api or win32con are installed.
    C compiler: gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/anaconda3/include -arch x86_64 -I/opt/anaconda3/include -arch x86_64
    
    creating build/temp.macosx-10.9-x86_64-3.7
    creating build/temp.macosx-10.9-x86_64-3.7/src
    creating build/temp.macosx-10.9-x86_64-3.7/src/albopictus
    compile options: '-I/usr/local/include -I/opt/anaconda3/include/python3.7m -c'
    gcc: src/albopictus/modelAalbopictus03.c
    gcc: src/albopictus/incubator03.c
    gcc -bundle -undefined dynamic_lookup -L/opt/anaconda3/lib -arch x86_64 -L/opt/anaconda3/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.9-x86_64-3.7/src/albopictus/incubator03.o build/temp.macosx-10.9-x86_64-3.7/src/albopictus/modelAalbopictus03.o -L/usr/local/lib -lgsl -lgslcblas -lstdc++ -o build/lib.macosx-10.9-x86_64-3.7/albopictus/modelAalbopictus03.cpython-37m-darwin.so
    ld: library not found for -lgsl
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: Command "gcc -bundle -undefined dynamic_lookup -L/opt/anaconda3/lib -arch x86_64 -L/opt/anaconda3/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.9-x86_64-3.7/src/albopictus/incubator03.o build/temp.macosx-10.9-x86_64-3.7/src/albopictus/modelAalbopictus03.o -L/usr/local/lib -lgsl -lgslcblas -lstdc++ -o build/lib.macosx-10.9-x86_64-3.7/albopictus/modelAalbopictus03.cpython-37m-darwin.so" failed with exit status 1
    ----------------------------------------
  Rolling back uninstall of albopictus
  Moving to /opt/anaconda3/lib/python3.7/site-packages/albopictus-0.3.dist-info/
   from /opt/anaconda3/lib/python3.7/site-packages/~lbopictus-0.3.dist-info
  Moving to /opt/anaconda3/lib/python3.7/site-packages/albopictus/
   from /opt/anaconda3/lib/python3.7/site-packages/~lbopictus
ERROR: Command errored out with exit status 1: /opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/d1/v9s6m4bj68vfdt_035d3qppw0000gn/T/pip-req-build-qop4t5wd/setup.py'"'"'; __file__='"'"'/private/var/folders/d1/v9s6m4bj68vfdt_035d3qppw0000gn/T/pip-req-build-qop4t5wd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/d1/v9s6m4bj68vfdt_035d3qppw0000gn/T/pip-record-3kvum1g8/install-record.txt --single-version-externally-managed --compile --install-headers /opt/anaconda3/include/python3.7m/albopictus Check the logs for full command output.
(base) LUISs-MacBook-Pro:~ lalfaro$ python
Python 3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import albopictus
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.7/site-packages/albopictus/__init__.py", line 71, in <module>
    from readModel import prepareModel
ModuleNotFoundError: No module named 'readModel'

**Comment by kerguler** [comment]
You seem to be missing the GSL library:

> ld: library not found for -lgsl

In order to test this, you could create a simple C file named **test.c** with the following lines

```
int main() {
    return 0;
}
```

and run

```
gcc -lgsl test.c
```

If you get the library not found linker error, please refer to the following thread for instructions on its installation:

[https://coral.ise.lehigh.edu/jild13/2016/07/11/hello/](url)

**Comment by lalfaroUNA** [comment]
Ok, thank you so much¡
