### ISSUE TITLE
ValueError on death rate

### ISSUE THREAD

**Issue by pantelisgeor** [kerguler/albopictus#4]
```
from albopictus.population import spop
import numpy as np

# Declare the survival function as defined in Eqn. 1
def death(pop):
    if pop.shape[1] == 0:
        return [480.0, 48.0]
    mn = 480.0 - 48.0 * pop[:, 1]
    mn[mn < 240.0] = 240.0
    return [mn, 0.1*mn]


# Create a stochastic population of class spop using the gamma distribution
vec = spop(stochastic=True, prob='gamma')

# Add 1000 individuals with age 0, devcycle 0 and development 0
vec.add([[0, 0, 0, 1000]])

pop_size = []
dev = []
# Iterate for 720 hours
for i in np.arange(720):
    # Calculate the death mean and standard deviation
    tmp = death(vec.pop)
    # Record the population size
    pop_size.append(vec.size)
    # Iterate for 1 time unit
    vec.iterate(dev_mean=50,
                dev_sd=10,
                death_mean=tmp[0],
                death_sd=tmp[1])
    # Record the total number of individuals completing development
    dev.append(vec.developed)
    # Reintroduce to the population all individuals which completed
    # their development for the next round of development
    vec.add(vec.devtable)

```

Running the example from the F1000 Research paper produces the following error:

Traceback (most recent call last):
  File "/home/***/miniconda3/envs/virtual_env2/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-b223e842c28e>", line 30, in <module>
    death_sd=tmp[1])
  File "/home/***/miniconda3/envs/virtual_env2/lib/python3.7/site-packages/albopictus/population/__init__.py", line 119, in iterate
    if (not (death_mean is None)) and ((death_sd is None) or death_sd == 0):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

The tmp list's dimensions (survival fraction) are not what is expected and this produces the above error. I'm running Python 3.7 and albopictus v.1.11 on Ubuntu 18.04.

**Comment by kerguler** [comment]
Thanks @pantelisgeor for pointing out this issue. Could you please check if the latest version (1.12.3) fixes the problem?

**Comment by pantelisgeor** [comment]
@kerguler I've installed v1.12.3 and it now works as expected, thank you very much for your prompt reply and action!
